### ISSUE TITLE
data_batch制作

### ISSUE THREAD

**Issue by gukangkang** [yhlleo/cifar10Dataset#1]
你好，非常感谢你的教程。在重现你的代码时发现了一个小问题，就是最终只能发现一个data_bacth,原因在于pickled.py文件中，Idx=0，需要放置在循环外。

**Comment by yhlleo** [comment]
You can set the data_batch count by changing the [`bin_num`](https://github.com/yhlleo/cifar10Dataset/blob/master/pickled.py#L17) value. 

It was set as `1` in the provided [demo.py](https://github.com/yhlleo/cifar10Dataset/blob/master/demo.py#L16). For your own dataset, it's up to you.

**Comment by yaxiongchi** [comment]
即使改了bin_num的值，也只能产生一个batch，因为Idx=0在循环里。Idx必须放在循环外，才能产生多个batch，代码错了。

**Comment by yhlleo** [comment]
多谢，已经修改过来了。@yaxiongchi
