### ISSUE TITLE
生成的数据集.bin 和 没有bin 有啥区别？

### ISSUE THREAD

**Issue by Arthur-Shi** [yhlleo/cifar10Dataset#4]
我按照demo.py运行了 生成的是 没有bin结尾的文件，但是 我觉得我直接加.bin在某些程序无法运行，到底有啥区别？

.bin 和 没有 有啥区别

**Comment by yhlleo** [comment]
没区别，只是文件名的区别，需要修改load data 的code

**Comment by Arthur-Shi** [comment]
那我直接在文件名上直接加.bin 就一致了？？？

**Comment by Arthur-Shi** [comment]
谢谢！！！
